# Generated by Django 3.2.5 on 2022-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pretty_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moblie', models.CharField(max_length=11, verbose_name='手机号码')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (2, '未占用')], verbose_name='状态')),
            ],
        ),
    ]
