# Generated by Django 3.2.5 on 2022-08-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=64, verbose_name='姓名'),
        ),
    ]
