# Generated by Django 3.2.5 on 2022-08-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20220809_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=64, verbose_name='级别')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.CharField(max_length=64, verbose_name='任务详情')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.admin', verbose_name='负责人')),
            ],
        ),
    ]
