# Generated by Django 3.2.5 on 2022-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '日常'), (2, '重要'), (3, '紧急')], default=1, verbose_name='级别'),
        ),
    ]
