# Generated by Django 3.2.5 on 2022-08-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_task_list_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=64, verbose_name='订单编号')),
                ('order_name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='商品状态')),
                ('order_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.admin', verbose_name='管理员')),
            ],
        ),
    ]
